[build]
  command = "npm run build"
  publish = "dist"

[functions]
  # Increase timeout for PDF generation functions
  # Default is 10 seconds, we need more for Puppeteer
  node_bundler = "esbuild"

# Environment variables (set these in Netlify UI)
# GEMINI_API_KEY
# SUPABASE_URL
# SUPABASE_KEY
# STRIPE_SECRET_KEY
# STRIPE_WEBHOOK_SECRET

